### ISSUE TITLE
Can't load StateManager, KeyError: 'file'

### ISSUE THREAD

**Issue by trietptm** [andreafioraldi/r2angrdbg#4]
Error with Python 2:
![image](https://user-images.githubusercontent.com/526959/59248402-8186a980-8c4c-11e9-81b8-fc2775449a2b.png)

Error with Python 3:
![image](https://user-images.githubusercontent.com/526959/59248438-9c591e00-8c4c-11e9-8a3c-e8c777a19b44.png)

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Python27\lib\site-packages\angrdbg\core.py", line 111, in __init__
>     self.state = StateShot(**kwargs) if state is None else state
>   File "C:\Python27\lib\site-packages\angrdbg\core.py", line 54, in StateShot
>     project = load_project()
>   File "C:\Python27\lib\site-packages\angrdbg\context.py", line 39, in load_project
>     return reload_project(input_file)
>   File "C:\Python27\lib\site-packages\angrdbg\context.py", line 29, in reload_project
>     input_file = debugger.input_file()
>   File "C:\Python27\lib\site-packages\r2angrdbg\__init__.py", line 48, in input_file
>     path = self.r2.cmdj("dmj")[0]["file"]
> KeyError: 'file'

**Comment by andreafioraldi** [comment]
r2 changes quickly, they changed the dmj command output in json.
Type dmj~{} in r2 and see what changed, I can't at the moment (I'm writing from the smartphone)

**Comment by trietptm** [comment]
Hi, I try to fix this error and another error:
![image](https://user-images.githubusercontent.com/526959/59251052-0f659300-8c53-11e9-9b41-4edb36393e4b.png)

in this pull request: https://github.com/andreafioraldi/r2angrdbg/pull/5
but now it raises another error:

![image](https://user-images.githubusercontent.com/526959/59251348-d11ca380-8c53-11e9-8ff8-8937aca3bf75.png)

**Comment by andreafioraldi** [comment]
Ok you are on Windows and this is an angrdbg issue.
I tested angrdbg very few times on Windows, I guess that the angr team added some functionalities to the Windows simos (It was poor when I developed angrdbg on angr 7) and this addition tries to map addresses already mapped in the debugger.
A debugger page is mapped lazily, this is a not-trivial problem cause if I let the simos to substitute the page maybe it will break some functions that are taken from the debugged process space, otherwise, if block the page remapping maybe I will break some Windows simprocedures.
I can't work on angrdbg now, if you need a working r2angrdbg ASAP an immediate and brutal fix may be just to remove the statement that cause this exception in page_8.py. I will introduce a new variable (like the memory type options) to let the user to enable or not page remapping in the next days.
